// <auto-generated />
using System;
using CoinPortal.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoinPortal.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoinPortal.Api.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionReminderSentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionReminderTriedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FinalDeletionReminderSentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSignInAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("PreferredAccent")
                        .HasColumnType("int");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<int?>("PreferredTheme")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PreviousSignInAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StorageWarningLevel")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("VerificationRequestSentAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("[NormalizedEmail] IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AspNetUsers_PreferredAccent", "[PreferredAccent] BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_AspNetUsers_PreferredTheme", "[PreferredTheme] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_AspNetUsers_StorageWarningLevel", "[StorageWarningLevel] BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("CoinPortal.Api.Data.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActorUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Setting")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TargetCollectionId")
                        .HasColumnType("int");

                    b.Property<string>("TargetCollectionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TargetUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("TargetUserId");

                    b.ToTable("AuditLog", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_Action", "[Action] IN (1, 2, 3, 4, 5, 6, 7, 8)");
                        });
                });

            modelBuilder.Entity("CoinPortal.Api.Data.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Denomination")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("FaceValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsCommemorative")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("MintMark")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("OwnerId");

                    b.HasIndex("CollectionId", "CountryCode", "Denomination", "Year");

                    b.ToTable("Coins", t =>
                        {
                            t.HasCheckConstraint("CK_Coins_Kind", "[Kind] IN (1, 2)");

                            t.HasCheckConstraint("CK_Coins_Quantity", "[Quantity] >= 1");

                            t.HasCheckConstraint("CK_Coins_Value", "([Kind] = 1 AND [Denomination] IN (1, 2, 5, 10, 20, 50, 100, 200) AND [FaceValue] IS NULL AND [Currency] IS NULL) OR ([Kind] = 2 AND [Denomination] IS NULL AND [FaceValue] > 0 AND [Currency] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Coins_Year", "([Kind] = 1 AND [Year] >= 1999) OR ([Kind] = 2 AND [Year] >= 1)");
                        });
                });

            modelBuilder.Entity("CoinPortal.Api.Data.CoinPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CoinId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CoinId", "Side")
                        .IsUnique();

                    b.ToTable("CoinPhotos", t =>
                        {
                            t.HasCheckConstraint("CK_CoinPhotos_Side", "[Side] IN (1, 2)");

                            t.HasCheckConstraint("CK_CoinPhotos_SizeBytes", "[SizeBytes] > 0");
                        });
                });

            modelBuilder.Entity("CoinPortal.Api.Data.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CoverImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CoverSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ModerationLockedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShareToken")
                        .HasMaxLength(22)
                        .IsUnicode(false)
                        .HasColumnType("char(22)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_BIN2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasFilter("[ShareToken] IS NOT NULL");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique();

                    b.HasIndex("Visibility", "OwnerId");

                    b.ToTable("Collections", t =>
                        {
                            t.HasCheckConstraint("CK_Collections_Visibility", "[Visibility] IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("CoinPortal.Api.Data.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<bool>("IsEuroIssuer")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Code = "AD",
                            IsEuroIssuer = true,
                            Name = "Andorra"
                        },
                        new
                        {
                            Code = "AE",
                            IsEuroIssuer = false,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Code = "AF",
                            IsEuroIssuer = false,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Code = "AG",
                            IsEuroIssuer = false,
                            Name = "Antigua & Barbuda"
                        },
                        new
                        {
                            Code = "AI",
                            IsEuroIssuer = false,
                            Name = "Anguilla"
                        },
                        new
                        {
                            Code = "AL",
                            IsEuroIssuer = false,
                            Name = "Albania"
                        },
                        new
                        {
                            Code = "AM",
                            IsEuroIssuer = false,
                            Name = "Armenia"
                        },
                        new
                        {
                            Code = "AO",
                            IsEuroIssuer = false,
                            Name = "Angola"
                        },
                        new
                        {
                            Code = "AQ",
                            IsEuroIssuer = false,
                            Name = "Antarctica"
                        },
                        new
                        {
                            Code = "AR",
                            IsEuroIssuer = false,
                            Name = "Argentina"
                        },
                        new
                        {
                            Code = "AS",
                            IsEuroIssuer = false,
                            Name = "American Samoa"
                        },
                        new
                        {
                            Code = "AT",
                            IsEuroIssuer = true,
                            Name = "Austria"
                        },
                        new
                        {
                            Code = "AU",
                            IsEuroIssuer = false,
                            Name = "Australia"
                        },
                        new
                        {
                            Code = "AW",
                            IsEuroIssuer = false,
                            Name = "Aruba"
                        },
                        new
                        {
                            Code = "AX",
                            IsEuroIssuer = false,
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Code = "AZ",
                            IsEuroIssuer = false,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Code = "BA",
                            IsEuroIssuer = false,
                            Name = "Bosnia & Herzegovina"
                        },
                        new
                        {
                            Code = "BB",
                            IsEuroIssuer = false,
                            Name = "Barbados"
                        },
                        new
                        {
                            Code = "BD",
                            IsEuroIssuer = false,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Code = "BE",
                            IsEuroIssuer = true,
                            Name = "Belgium"
                        },
                        new
                        {
                            Code = "BF",
                            IsEuroIssuer = false,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Code = "BG",
                            IsEuroIssuer = true,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Code = "BH",
                            IsEuroIssuer = false,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Code = "BI",
                            IsEuroIssuer = false,
                            Name = "Burundi"
                        },
                        new
                        {
                            Code = "BJ",
                            IsEuroIssuer = false,
                            Name = "Benin"
                        },
                        new
                        {
                            Code = "BL",
                            IsEuroIssuer = false,
                            Name = "St. Barthélemy"
                        },
                        new
                        {
                            Code = "BM",
                            IsEuroIssuer = false,
                            Name = "Bermuda"
                        },
                        new
                        {
                            Code = "BN",
                            IsEuroIssuer = false,
                            Name = "Brunei"
                        },
                        new
                        {
                            Code = "BO",
                            IsEuroIssuer = false,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Code = "BQ",
                            IsEuroIssuer = false,
                            Name = "Caribbean Netherlands"
                        },
                        new
                        {
                            Code = "BR",
                            IsEuroIssuer = false,
                            Name = "Brazil"
                        },
                        new
                        {
                            Code = "BS",
                            IsEuroIssuer = false,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Code = "BT",
                            IsEuroIssuer = false,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Code = "BV",
                            IsEuroIssuer = false,
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Code = "BW",
                            IsEuroIssuer = false,
                            Name = "Botswana"
                        },
                        new
                        {
                            Code = "BY",
                            IsEuroIssuer = false,
                            Name = "Belarus"
                        },
                        new
                        {
                            Code = "BZ",
                            IsEuroIssuer = false,
                            Name = "Belize"
                        },
                        new
                        {
                            Code = "CA",
                            IsEuroIssuer = false,
                            Name = "Canada"
                        },
                        new
                        {
                            Code = "CC",
                            IsEuroIssuer = false,
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Code = "CD",
                            IsEuroIssuer = false,
                            Name = "Congo - Kinshasa"
                        },
                        new
                        {
                            Code = "CF",
                            IsEuroIssuer = false,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Code = "CG",
                            IsEuroIssuer = false,
                            Name = "Congo - Brazzaville"
                        },
                        new
                        {
                            Code = "CH",
                            IsEuroIssuer = false,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Code = "CI",
                            IsEuroIssuer = false,
                            Name = "Côte d’Ivoire"
                        },
                        new
                        {
                            Code = "CK",
                            IsEuroIssuer = false,
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Code = "CL",
                            IsEuroIssuer = false,
                            Name = "Chile"
                        },
                        new
                        {
                            Code = "CM",
                            IsEuroIssuer = false,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Code = "CN",
                            IsEuroIssuer = false,
                            Name = "China"
                        },
                        new
                        {
                            Code = "CO",
                            IsEuroIssuer = false,
                            Name = "Colombia"
                        },
                        new
                        {
                            Code = "CR",
                            IsEuroIssuer = false,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Code = "CS",
                            IsEuroIssuer = false,
                            Name = "Czechoslovakia"
                        },
                        new
                        {
                            Code = "CU",
                            IsEuroIssuer = false,
                            Name = "Cuba"
                        },
                        new
                        {
                            Code = "CV",
                            IsEuroIssuer = false,
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Code = "CW",
                            IsEuroIssuer = false,
                            Name = "Curaçao"
                        },
                        new
                        {
                            Code = "CX",
                            IsEuroIssuer = false,
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Code = "CY",
                            IsEuroIssuer = true,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Code = "CZ",
                            IsEuroIssuer = false,
                            Name = "Czechia"
                        },
                        new
                        {
                            Code = "DD",
                            IsEuroIssuer = false,
                            Name = "East Germany"
                        },
                        new
                        {
                            Code = "DE",
                            IsEuroIssuer = true,
                            Name = "Germany"
                        },
                        new
                        {
                            Code = "DJ",
                            IsEuroIssuer = false,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Code = "DK",
                            IsEuroIssuer = false,
                            Name = "Denmark"
                        },
                        new
                        {
                            Code = "DM",
                            IsEuroIssuer = false,
                            Name = "Dominica"
                        },
                        new
                        {
                            Code = "DO",
                            IsEuroIssuer = false,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Code = "DZ",
                            IsEuroIssuer = false,
                            Name = "Algeria"
                        },
                        new
                        {
                            Code = "EC",
                            IsEuroIssuer = false,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Code = "EE",
                            IsEuroIssuer = true,
                            Name = "Estonia"
                        },
                        new
                        {
                            Code = "EG",
                            IsEuroIssuer = false,
                            Name = "Egypt"
                        },
                        new
                        {
                            Code = "EH",
                            IsEuroIssuer = false,
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Code = "ER",
                            IsEuroIssuer = false,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Code = "ES",
                            IsEuroIssuer = true,
                            Name = "Spain"
                        },
                        new
                        {
                            Code = "ET",
                            IsEuroIssuer = false,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Code = "FI",
                            IsEuroIssuer = true,
                            Name = "Finland"
                        },
                        new
                        {
                            Code = "FJ",
                            IsEuroIssuer = false,
                            Name = "Fiji"
                        },
                        new
                        {
                            Code = "FK",
                            IsEuroIssuer = false,
                            Name = "Falkland Islands"
                        },
                        new
                        {
                            Code = "FM",
                            IsEuroIssuer = false,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Code = "FO",
                            IsEuroIssuer = false,
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Code = "FR",
                            IsEuroIssuer = true,
                            Name = "France"
                        },
                        new
                        {
                            Code = "GA",
                            IsEuroIssuer = false,
                            Name = "Gabon"
                        },
                        new
                        {
                            Code = "GB",
                            IsEuroIssuer = false,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Code = "GD",
                            IsEuroIssuer = false,
                            Name = "Grenada"
                        },
                        new
                        {
                            Code = "GE",
                            IsEuroIssuer = false,
                            Name = "Georgia"
                        },
                        new
                        {
                            Code = "GF",
                            IsEuroIssuer = false,
                            Name = "French Guiana"
                        },
                        new
                        {
                            Code = "GG",
                            IsEuroIssuer = false,
                            Name = "Guernsey"
                        },
                        new
                        {
                            Code = "GH",
                            IsEuroIssuer = false,
                            Name = "Ghana"
                        },
                        new
                        {
                            Code = "GI",
                            IsEuroIssuer = false,
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Code = "GL",
                            IsEuroIssuer = false,
                            Name = "Greenland"
                        },
                        new
                        {
                            Code = "GM",
                            IsEuroIssuer = false,
                            Name = "Gambia"
                        },
                        new
                        {
                            Code = "GN",
                            IsEuroIssuer = false,
                            Name = "Guinea"
                        },
                        new
                        {
                            Code = "GP",
                            IsEuroIssuer = false,
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Code = "GQ",
                            IsEuroIssuer = false,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Code = "GR",
                            IsEuroIssuer = true,
                            Name = "Greece"
                        },
                        new
                        {
                            Code = "GS",
                            IsEuroIssuer = false,
                            Name = "South Georgia & South Sandwich Islands"
                        },
                        new
                        {
                            Code = "GT",
                            IsEuroIssuer = false,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Code = "GU",
                            IsEuroIssuer = false,
                            Name = "Guam"
                        },
                        new
                        {
                            Code = "GW",
                            IsEuroIssuer = false,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Code = "GY",
                            IsEuroIssuer = false,
                            Name = "Guyana"
                        },
                        new
                        {
                            Code = "HK",
                            IsEuroIssuer = false,
                            Name = "Hong Kong SAR China"
                        },
                        new
                        {
                            Code = "HM",
                            IsEuroIssuer = false,
                            Name = "Heard & McDonald Islands"
                        },
                        new
                        {
                            Code = "HN",
                            IsEuroIssuer = false,
                            Name = "Honduras"
                        },
                        new
                        {
                            Code = "HR",
                            IsEuroIssuer = true,
                            Name = "Croatia"
                        },
                        new
                        {
                            Code = "HT",
                            IsEuroIssuer = false,
                            Name = "Haiti"
                        },
                        new
                        {
                            Code = "HU",
                            IsEuroIssuer = false,
                            Name = "Hungary"
                        },
                        new
                        {
                            Code = "ID",
                            IsEuroIssuer = false,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Code = "IE",
                            IsEuroIssuer = true,
                            Name = "Ireland"
                        },
                        new
                        {
                            Code = "IL",
                            IsEuroIssuer = false,
                            Name = "Israel"
                        },
                        new
                        {
                            Code = "IM",
                            IsEuroIssuer = false,
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Code = "IN",
                            IsEuroIssuer = false,
                            Name = "India"
                        },
                        new
                        {
                            Code = "IO",
                            IsEuroIssuer = false,
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Code = "IQ",
                            IsEuroIssuer = false,
                            Name = "Iraq"
                        },
                        new
                        {
                            Code = "IR",
                            IsEuroIssuer = false,
                            Name = "Iran"
                        },
                        new
                        {
                            Code = "IS",
                            IsEuroIssuer = false,
                            Name = "Iceland"
                        },
                        new
                        {
                            Code = "IT",
                            IsEuroIssuer = true,
                            Name = "Italy"
                        },
                        new
                        {
                            Code = "JE",
                            IsEuroIssuer = false,
                            Name = "Jersey"
                        },
                        new
                        {
                            Code = "JM",
                            IsEuroIssuer = false,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Code = "JO",
                            IsEuroIssuer = false,
                            Name = "Jordan"
                        },
                        new
                        {
                            Code = "JP",
                            IsEuroIssuer = false,
                            Name = "Japan"
                        },
                        new
                        {
                            Code = "KE",
                            IsEuroIssuer = false,
                            Name = "Kenya"
                        },
                        new
                        {
                            Code = "KG",
                            IsEuroIssuer = false,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Code = "KH",
                            IsEuroIssuer = false,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Code = "KI",
                            IsEuroIssuer = false,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Code = "KM",
                            IsEuroIssuer = false,
                            Name = "Comoros"
                        },
                        new
                        {
                            Code = "KN",
                            IsEuroIssuer = false,
                            Name = "St. Kitts & Nevis"
                        },
                        new
                        {
                            Code = "KP",
                            IsEuroIssuer = false,
                            Name = "North Korea"
                        },
                        new
                        {
                            Code = "KR",
                            IsEuroIssuer = false,
                            Name = "South Korea"
                        },
                        new
                        {
                            Code = "KW",
                            IsEuroIssuer = false,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Code = "KY",
                            IsEuroIssuer = false,
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Code = "KZ",
                            IsEuroIssuer = false,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Code = "LA",
                            IsEuroIssuer = false,
                            Name = "Laos"
                        },
                        new
                        {
                            Code = "LB",
                            IsEuroIssuer = false,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Code = "LC",
                            IsEuroIssuer = false,
                            Name = "St. Lucia"
                        },
                        new
                        {
                            Code = "LI",
                            IsEuroIssuer = false,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Code = "LK",
                            IsEuroIssuer = false,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Code = "LR",
                            IsEuroIssuer = false,
                            Name = "Liberia"
                        },
                        new
                        {
                            Code = "LS",
                            IsEuroIssuer = false,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Code = "LT",
                            IsEuroIssuer = true,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Code = "LU",
                            IsEuroIssuer = true,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Code = "LV",
                            IsEuroIssuer = true,
                            Name = "Latvia"
                        },
                        new
                        {
                            Code = "LY",
                            IsEuroIssuer = false,
                            Name = "Libya"
                        },
                        new
                        {
                            Code = "MA",
                            IsEuroIssuer = false,
                            Name = "Morocco"
                        },
                        new
                        {
                            Code = "MC",
                            IsEuroIssuer = true,
                            Name = "Monaco"
                        },
                        new
                        {
                            Code = "MD",
                            IsEuroIssuer = false,
                            Name = "Moldova"
                        },
                        new
                        {
                            Code = "ME",
                            IsEuroIssuer = false,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Code = "MF",
                            IsEuroIssuer = false,
                            Name = "St. Martin"
                        },
                        new
                        {
                            Code = "MG",
                            IsEuroIssuer = false,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Code = "MH",
                            IsEuroIssuer = false,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Code = "MK",
                            IsEuroIssuer = false,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Code = "ML",
                            IsEuroIssuer = false,
                            Name = "Mali"
                        },
                        new
                        {
                            Code = "MM",
                            IsEuroIssuer = false,
                            Name = "Myanmar (Burma)"
                        },
                        new
                        {
                            Code = "MN",
                            IsEuroIssuer = false,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Code = "MO",
                            IsEuroIssuer = false,
                            Name = "Macao SAR China"
                        },
                        new
                        {
                            Code = "MP",
                            IsEuroIssuer = false,
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Code = "MQ",
                            IsEuroIssuer = false,
                            Name = "Martinique"
                        },
                        new
                        {
                            Code = "MR",
                            IsEuroIssuer = false,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Code = "MS",
                            IsEuroIssuer = false,
                            Name = "Montserrat"
                        },
                        new
                        {
                            Code = "MT",
                            IsEuroIssuer = true,
                            Name = "Malta"
                        },
                        new
                        {
                            Code = "MU",
                            IsEuroIssuer = false,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Code = "MV",
                            IsEuroIssuer = false,
                            Name = "Maldives"
                        },
                        new
                        {
                            Code = "MW",
                            IsEuroIssuer = false,
                            Name = "Malawi"
                        },
                        new
                        {
                            Code = "MX",
                            IsEuroIssuer = false,
                            Name = "Mexico"
                        },
                        new
                        {
                            Code = "MY",
                            IsEuroIssuer = false,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Code = "MZ",
                            IsEuroIssuer = false,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Code = "NA",
                            IsEuroIssuer = false,
                            Name = "Namibia"
                        },
                        new
                        {
                            Code = "NC",
                            IsEuroIssuer = false,
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Code = "NE",
                            IsEuroIssuer = false,
                            Name = "Niger"
                        },
                        new
                        {
                            Code = "NF",
                            IsEuroIssuer = false,
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Code = "NG",
                            IsEuroIssuer = false,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Code = "NI",
                            IsEuroIssuer = false,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Code = "NL",
                            IsEuroIssuer = true,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Code = "NO",
                            IsEuroIssuer = false,
                            Name = "Norway"
                        },
                        new
                        {
                            Code = "NP",
                            IsEuroIssuer = false,
                            Name = "Nepal"
                        },
                        new
                        {
                            Code = "NR",
                            IsEuroIssuer = false,
                            Name = "Nauru"
                        },
                        new
                        {
                            Code = "NU",
                            IsEuroIssuer = false,
                            Name = "Niue"
                        },
                        new
                        {
                            Code = "NZ",
                            IsEuroIssuer = false,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Code = "OM",
                            IsEuroIssuer = false,
                            Name = "Oman"
                        },
                        new
                        {
                            Code = "PA",
                            IsEuroIssuer = false,
                            Name = "Panama"
                        },
                        new
                        {
                            Code = "PE",
                            IsEuroIssuer = false,
                            Name = "Peru"
                        },
                        new
                        {
                            Code = "PF",
                            IsEuroIssuer = false,
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Code = "PG",
                            IsEuroIssuer = false,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Code = "PH",
                            IsEuroIssuer = false,
                            Name = "Philippines"
                        },
                        new
                        {
                            Code = "PK",
                            IsEuroIssuer = false,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Code = "PL",
                            IsEuroIssuer = false,
                            Name = "Poland"
                        },
                        new
                        {
                            Code = "PM",
                            IsEuroIssuer = false,
                            Name = "St. Pierre & Miquelon"
                        },
                        new
                        {
                            Code = "PN",
                            IsEuroIssuer = false,
                            Name = "Pitcairn Islands"
                        },
                        new
                        {
                            Code = "PR",
                            IsEuroIssuer = false,
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Code = "PS",
                            IsEuroIssuer = false,
                            Name = "Palestinian Territories"
                        },
                        new
                        {
                            Code = "PT",
                            IsEuroIssuer = true,
                            Name = "Portugal"
                        },
                        new
                        {
                            Code = "PW",
                            IsEuroIssuer = false,
                            Name = "Palau"
                        },
                        new
                        {
                            Code = "PY",
                            IsEuroIssuer = false,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Code = "QA",
                            IsEuroIssuer = false,
                            Name = "Qatar"
                        },
                        new
                        {
                            Code = "RE",
                            IsEuroIssuer = false,
                            Name = "Réunion"
                        },
                        new
                        {
                            Code = "RO",
                            IsEuroIssuer = false,
                            Name = "Romania"
                        },
                        new
                        {
                            Code = "RS",
                            IsEuroIssuer = false,
                            Name = "Serbia"
                        },
                        new
                        {
                            Code = "RU",
                            IsEuroIssuer = false,
                            Name = "Russia"
                        },
                        new
                        {
                            Code = "RW",
                            IsEuroIssuer = false,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Code = "SA",
                            IsEuroIssuer = false,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Code = "SB",
                            IsEuroIssuer = false,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Code = "SC",
                            IsEuroIssuer = false,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Code = "SD",
                            IsEuroIssuer = false,
                            Name = "Sudan"
                        },
                        new
                        {
                            Code = "SE",
                            IsEuroIssuer = false,
                            Name = "Sweden"
                        },
                        new
                        {
                            Code = "SG",
                            IsEuroIssuer = false,
                            Name = "Singapore"
                        },
                        new
                        {
                            Code = "SH",
                            IsEuroIssuer = false,
                            Name = "St. Helena"
                        },
                        new
                        {
                            Code = "SI",
                            IsEuroIssuer = true,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Code = "SJ",
                            IsEuroIssuer = false,
                            Name = "Svalbard & Jan Mayen"
                        },
                        new
                        {
                            Code = "SK",
                            IsEuroIssuer = true,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Code = "SL",
                            IsEuroIssuer = false,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Code = "SM",
                            IsEuroIssuer = true,
                            Name = "San Marino"
                        },
                        new
                        {
                            Code = "SN",
                            IsEuroIssuer = false,
                            Name = "Senegal"
                        },
                        new
                        {
                            Code = "SO",
                            IsEuroIssuer = false,
                            Name = "Somalia"
                        },
                        new
                        {
                            Code = "SR",
                            IsEuroIssuer = false,
                            Name = "Suriname"
                        },
                        new
                        {
                            Code = "SS",
                            IsEuroIssuer = false,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Code = "ST",
                            IsEuroIssuer = false,
                            Name = "São Tomé & Príncipe"
                        },
                        new
                        {
                            Code = "SU",
                            IsEuroIssuer = false,
                            Name = "Soviet Union"
                        },
                        new
                        {
                            Code = "SV",
                            IsEuroIssuer = false,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Code = "SX",
                            IsEuroIssuer = false,
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            Code = "SY",
                            IsEuroIssuer = false,
                            Name = "Syria"
                        },
                        new
                        {
                            Code = "SZ",
                            IsEuroIssuer = false,
                            Name = "Eswatini"
                        },
                        new
                        {
                            Code = "TC",
                            IsEuroIssuer = false,
                            Name = "Turks & Caicos Islands"
                        },
                        new
                        {
                            Code = "TD",
                            IsEuroIssuer = false,
                            Name = "Chad"
                        },
                        new
                        {
                            Code = "TF",
                            IsEuroIssuer = false,
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Code = "TG",
                            IsEuroIssuer = false,
                            Name = "Togo"
                        },
                        new
                        {
                            Code = "TH",
                            IsEuroIssuer = false,
                            Name = "Thailand"
                        },
                        new
                        {
                            Code = "TJ",
                            IsEuroIssuer = false,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Code = "TK",
                            IsEuroIssuer = false,
                            Name = "Tokelau"
                        },
                        new
                        {
                            Code = "TL",
                            IsEuroIssuer = false,
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Code = "TM",
                            IsEuroIssuer = false,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Code = "TN",
                            IsEuroIssuer = false,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Code = "TO",
                            IsEuroIssuer = false,
                            Name = "Tonga"
                        },
                        new
                        {
                            Code = "TR",
                            IsEuroIssuer = false,
                            Name = "Türkiye"
                        },
                        new
                        {
                            Code = "TT",
                            IsEuroIssuer = false,
                            Name = "Trinidad & Tobago"
                        },
                        new
                        {
                            Code = "TV",
                            IsEuroIssuer = false,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Code = "TW",
                            IsEuroIssuer = false,
                            Name = "Taiwan"
                        },
                        new
                        {
                            Code = "TZ",
                            IsEuroIssuer = false,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Code = "UA",
                            IsEuroIssuer = false,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Code = "UG",
                            IsEuroIssuer = false,
                            Name = "Uganda"
                        },
                        new
                        {
                            Code = "UM",
                            IsEuroIssuer = false,
                            Name = "U.S. Outlying Islands"
                        },
                        new
                        {
                            Code = "US",
                            IsEuroIssuer = false,
                            Name = "United States"
                        },
                        new
                        {
                            Code = "UY",
                            IsEuroIssuer = false,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Code = "UZ",
                            IsEuroIssuer = false,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Code = "VA",
                            IsEuroIssuer = true,
                            Name = "Vatican City"
                        },
                        new
                        {
                            Code = "VC",
                            IsEuroIssuer = false,
                            Name = "St. Vincent & Grenadines"
                        },
                        new
                        {
                            Code = "VE",
                            IsEuroIssuer = false,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Code = "VG",
                            IsEuroIssuer = false,
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Code = "VI",
                            IsEuroIssuer = false,
                            Name = "U.S. Virgin Islands"
                        },
                        new
                        {
                            Code = "VN",
                            IsEuroIssuer = false,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Code = "VU",
                            IsEuroIssuer = false,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Code = "WF",
                            IsEuroIssuer = false,
                            Name = "Wallis & Futuna"
                        },
                        new
                        {
                            Code = "WS",
                            IsEuroIssuer = false,
                            Name = "Samoa"
                        },
                        new
                        {
                            Code = "YE",
                            IsEuroIssuer = false,
                            Name = "Yemen"
                        },
                        new
                        {
                            Code = "YT",
                            IsEuroIssuer = false,
                            Name = "Mayotte"
                        },
                        new
                        {
                            Code = "YU",
                            IsEuroIssuer = false,
                            Name = "Yugoslavia"
                        },
                        new
                        {
                            Code = "ZA",
                            IsEuroIssuer = false,
                            Name = "South Africa"
                        },
                        new
                        {
                            Code = "ZM",
                            IsEuroIssuer = false,
                            Name = "Zambia"
                        },
                        new
                        {
                            Code = "ZW",
                            IsEuroIssuer = false,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("CoinPortal.Api.Data.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("MinPublicCoins")
                        .HasColumnType("int");

                    b.Property<int>("UnverifiedLifetimeDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("UnverifiedLifetimeSinceUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnverifiedMaxCoins")
                        .HasColumnType("int");

                    b.Property<int>("UserQuotaMegabytes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings", t =>
                        {
                            t.HasCheckConstraint("CK_SiteSettings_Id", "[Id] = 1");

                            t.HasCheckConstraint("CK_SiteSettings_MinPublicCoins", "[MinPublicCoins] BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_SiteSettings_UnverifiedLifetimeDays", "[UnverifiedLifetimeDays] BETWEEN 0 AND 365");

                            t.HasCheckConstraint("CK_SiteSettings_UnverifiedMaxCoins", "[UnverifiedMaxCoins] BETWEEN 0 AND 10000");

                            t.HasCheckConstraint("CK_SiteSettings_UserQuotaMegabytes", "[UserQuotaMegabytes] BETWEEN 50 AND 2000");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CoinPortal.Api.Data.Coin", b =>
                {
                    b.HasOne("CoinPortal.Api.Data.Collection", "Collection")
                        .WithMany("Coins")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoinPortal.Api.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoinPortal.Api.Data.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Country");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CoinPortal.Api.Data.CoinPhoto", b =>
                {
                    b.HasOne("CoinPortal.Api.Data.Coin", "Coin")
                        .WithMany("Photos")
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coin");
                });

            modelBuilder.Entity("CoinPortal.Api.Data.Collection", b =>
                {
                    b.HasOne("CoinPortal.Api.Data.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CoinPortal.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CoinPortal.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoinPortal.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CoinPortal.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoinPortal.Api.Data.Coin", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("CoinPortal.Api.Data.Collection", b =>
                {
                    b.Navigation("Coins");
                });
#pragma warning restore 612, 618
        }
    }
}
